web/router.ex
defmodule SpreedlyAirlines.Router do
  use SpreedlyAirlines.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", SpreedlyAirlines do
    pipe_through :browser # Use the default browser stack

    get "/", FlightController, :index
    get "/flights/:id", FlightController, :show
    get "/book/:flight_id", BookingController, :new
    post "/book/", BookingController, :create
    put "/book/", BookingController, :create      # this is on purpose, every additional attempt is logged as a new transaction
    get "/receipt/:id", BookingController, :show

    get "/log", TransactionController, :index
    get "/log/:id", TransactionController, :show
  end

  # Other scopes may use custom stacks.
  # scope "/api", SpreedlyAirlines do
  #   pipe_through :api
  # end
end

web/models/flight.ex
defmodule SpreedlyAirlines.Flight do
  @moduledoc """
  A defined Flight one can purchase
  """

  use SpreedlyAirlines.Web, :model
  import Number.Currency

  schema "flights" do
    field :departure_airport, :string
    field :arrival_airport, :string
    field :departure_time, Ecto.Time
    field :arrival_time, Ecto.Time
    field :price, :float
    field :vendor, :string

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:departure_airport, :arrival_airport, :departure_time, :arrival_time, :price, :vendor])
    |> validate_required([:departure_airport, :arrival_airport, :departure_time, :arrival_time, :price])
  end

  def formatted_price(%SpreedlyAirlines.Flight{price: price}), do: number_to_currency(price)

  def display_vendor(%SpreedlyAirlines.Flight{vendor: vendor}) when vendor == "" or is_nil(vendor), do: ""

  def display_vendor(%SpreedlyAirlines.Flight{vendor: vendor}) when vendor != "", do: " (" <> vendor <> ")"
end

web/controllers/flight_controller.ex
defmodule SpreedlyAirlines.FlightController do
  use SpreedlyAirlines.Web, :controller

  alias SpreedlyAirlines.Flight

  def index(conn, _params) do
    flights = Repo.all(Flight)
    render(conn, "index.html", flights: flights)
  end

  def show(conn, %{"id" => id}) do
    flight = Repo.get!(Flight, id)
    render(conn, "show.html", flight: flight)
  end

end

web/views/flight_view.ex
defmodule SpreedlyAirlines.FlightView do
  use SpreedlyAirlines.Web, :view
end

web/templates/flight/index.html.eex
<h2>Listing flights</h2>

<table class="table">
  <thead>
    <tr>
      <th>Departure airport</th>
      <th>Arrival airport</th>
      <th>Departure time</th>
      <th>Arrival time</th>
      <th>Price</th>
      <th></th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for flight <- @flights do %>
    <tr>
      <td><%= flight.departure_airport %></td>
      <td><%= flight.arrival_airport %></td>
      <td><%= flight.departure_time %></td>
      <td><%= flight.arrival_time %></td>
      <td><%= SpreedlyAirlines.Flight.formatted_price(flight) %></td>
      <td><%= SpreedlyAirlines.Flight.display_vendor(flight) %></td>

      <td class="text-right">
        <%= link "Book", to: flight_path(@conn, :show, flight), class: "btn btn-default btn-xs" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

web/templates/flight/show.html.eex
<h2>Flight Details: <%= @flight.departure_time %> <%= @flight.departure_airport %> to <%= @flight.arrival_airport %></h2>

<ul>

  <li>
    <strong>Departure airport:</strong>
    <%= @flight.departure_airport %>
  </li>

  <li>
    <strong>Arrival airport:</strong>
    <%= @flight.arrival_airport %>
  </li>

  <li>
    <strong>Departure time:</strong>
    <%= @flight.departure_time %>
  </li>

  <li>
    <strong>Arrival time:</strong>
    <%= @flight.arrival_time %>
  </li>

  <li>
    <strong>Price:</strong>
    <%= SpreedlyAirlines.Flight.formatted_price(@flight) %>
    <%= SpreedlyAirlines.Flight.display_vendor(@flight) %>
  </li>

</ul>
<%= link "Book It!", to: booking_path(@conn, :new, @flight), class: "btn btn-default" %><br />
<br />
<%= link "Back", to: flight_path(@conn, :index) %>