web/router.ex
defmodule SpreedlyAirlines.Router do
  use SpreedlyAirlines.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", SpreedlyAirlines do
    pipe_through :browser # Use the default browser stack

    get "/", FlightController, :index
    get "/flights/:id", FlightController, :show
    get "/book/:flight_id", BookingController, :new
    post "/book/", BookingController, :create
    put "/book/", BookingController, :create      # this is on purpose, every additional attempt is logged as a new transaction
    get "/receipt/:id", BookingController, :show

    get "/log", TransactionController, :index
    get "/log/:id", TransactionController, :show
  end

  # Other scopes may use custom stacks.
  # scope "/api", SpreedlyAirlines do
  #   pipe_through :api
  # end
end

web/controllers/transaction_controller.ex
defmodule SpreedlyAirlines.TransactionController do
  use SpreedlyAirlines.Web, :controller

  alias SpreedlyAirlines.Booking
  alias SpreedlyAirlines.Flight

  def index(conn, _params) do
    query = from Booking, order_by: [desc: :id]
    bookings = Repo.all(query)
    render(conn, "index.html", bookings: bookings)
  end

  def show(conn, %{"id" => id}) do
    booking = Repo.get!(Booking, id)
    flight = Repo.get!(Flight, booking.flight_id)
    render(conn, "show.html", booking: booking, flight: flight)
  end

end

web/views/transaction_view.ex
defmodule SpreedlyAirlines.TransactionView do
  use SpreedlyAirlines.Web, :view
end

web/templates/transaction/index.html.eex
<h2>Transaction History</h2>

<table class="table">
  <thead>
    <tr>
      <th>Id</td>
      <th>Flight</th>
      <th>Status message</th>
      <th>Username</th>
      <th>Amount</th>
      <th>Purchase Succeeded</th>
      <th>Purchase At</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for booking <- @bookings do %>
    <tr>
      <td><%= booking.id %></td>
      <td><%= booking.flight_id %></td>
      <td><%= booking.status_message %></td>
      <td><%= booking.username %></td>
      <td><%= SpreedlyAirlines.Booking.formatted_price(booking) %></td>
      <td><%= booking.purchase_succeeded %></td>
      <td><%= booking.purchase_at %></td>

      <td class="text-right">
        <%= link "Show", to: transaction_path(@conn, :show, booking), class: "btn btn-default btn-xs" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

web/templates/transaction/show.html.eex
<h2>Transaction Details</h2>

<ul>

  <li>
    <strong>Flight:</strong>
    <%= @booking.flight_id %> (<%= @flight.departure_airport%> to <%= @flight.arrival_airport %> at <%= @flight.departure_time %>)
    <%= SpreedlyAirlines.Flight.display_vendor(@flight) %>
  </li>

  <li>
    <strong>Status message:</strong>
    <%= @booking.status_message %>
  </li>

  <li>
    <strong>Username:</strong>
    <%= @booking.username %>
  </li>

  <li>
    <strong>Amount:</strong>
    <%= SpreedlyAirlines.Booking.formatted_price(@booking) %>
  </li>

  <li>
    <strong>Payment token:</strong>
    <%= @booking.payment_token %>
  </li>

  <li>
    <strong>CC Retained:</strong>
    <%= @booking.retain_cc %>
  </li>

  <li>
    <strong>Purchase Success?</strong>
    <%= @booking.purchase_succeeded %>
  </li>

  <li>
    <strong>Purchase Date:</strong>
    <%= @booking.purchase_at %>
  </li>

  <li>
    <strong>Purchase Number:</strong>
    <%= @booking.purchase_payment_method_number %>
  </li>

  <li>
    <strong>Purchase Gateway Transaction Id:</strong>
    <%= @booking.purchase_gateway_transaction_id %>
  </li>

  <li>
    <strong>Purchase Payment Method Token:</strong>
    <%= @booking.purchase_payment_method_token %>
  </li>

</ul>

<%= link "Back", to: transaction_path(@conn, :index) %>